version: '2'
services:
    jhipstermonolithicsample-app:
        image: jhipstermonolithicsample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstermonolithicsample-mysql:3306/jhipstermonolithicsample?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipstermonolithicsample-elasticsearch:9300
        ports:
            - 8080:8080
    jhipstermonolithicsample-mysql:
        extends:
            file: mysql.yml
            service: jhipstermonolithicsample-mysql
    jhipstermonolithicsample-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipstermonolithicsample-elasticsearch
